assets/database_languages.json
`.mjs` is becoming the standard extension for Node.js ES2015 module system.
=> Add .mjs as file extension for JavaScript

processor/processor.go, scripts/include.go
I was trying to add a new language definition to languages.json but, as
is with json, the pesky commas and other syntax was getting in the way.
When running `go generate` invalid JSON is encoded into constants.go and
then scc would just silently igore the error.  As a result no language
definitions would load.
This add some basic JSON validation to the go generate process as well
as exposes some other possible errors.  It also will generate the
constants to a temporary file before copying over making the process
more atomic and not clobbering a file on a failure.
Since there is now json validation a panic as added to scc itself to
barf if it can't read the json data.
=> validate languages.json during constants generation

processor/processor.go, processor/processor_test.go, processor/structs.go, processor/workers.go, processor/workers_test.go
Here's a quick PR (related to #17) that i worked with this afternoon that is minimalistic. I experimented with passing in an `io.Reader` instead of a `[]byte` but it was a bit invasive so I decided to hold off.
As part of this change, I'd like to support an optional callback that can be set on the FileJob that allows you to get per line parsing information which is important for my use case.  If not provided, works the same as today.
=> Proposed changes to support API

processor/workers.go, processor/workers_test.go
We don't have a mask for endComment matching, and the single line
comment mask got dropped in when I was find/replacing stuff. Using 0xFF
as a mask will match anything, which is a quick fix.
=> fix regression in some multiline comment parsing

processor/file.go, processor/formatters.go, processor/formatters_test.go, processor/processor.go, processor/workers.go
scc was starting to be capable of launching goroutines at a rate which
can lead to launching too many OS threads:
* linux-4.19-rc1 on a 16 core c5.4xlarge:
runtime: failed to create new OS thread (have 4090 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc
this change bounds the number of goroutine workers to avoid this, while
still creating enough to saturate the CPU. This includes a marginal
improvement in performance, and appears to make the runtime much more
consistent:
* linux-4.19-rc1 on a 4 core c5.xlarge:
before: Time (mean ± σ):      4.680 s ±  0.727 s    [User: 17.920 s, System: 0.632 s]
after:  Time (mean ± σ):      4.532 s ±  0.005 s    [User: 17.340 s, System: 0.705 s]
=> bound goroutine counts

processor/processor.go, processor/structs.go, processor/workers.go, processor/workers_test.go
Replaces matching of [][]byte slices with a trie / prefix tree.
Invalidates the need for pre-checking with bitmasks or otherwise.
Improves performance by ~15% in my testing:
4 cores, master: Time (mean ± σ):      6.360 s ±  0.007 s    [User: 24.677 s, System: 0.679 s]
4 cores, tries:  Time (mean ± σ):      5.489 s ±  0.008 s    [User: 21.145 s, System: 0.690 s]
8 cores, master: Time (mean ± σ):      3.217 s ±  0.005 s    [User: 24.840 s, System: 0.708 s]
8 cores, tries:  Time (mean ± σ):      2.784 s ±  0.005 s    [User: 21.270 s, System: 0.733 s]
16 cores, master: Time (mean ± σ):      1.660 s ±  0.016 s    [User: 24.936 s, System: 0.778 s]
16 cores, tries:  Time (mean ± σ):      1.446 s ±  0.014 s    [User: 21.378 s, System: 0.801 s]
=> implement tries for token matching

processor/workers.go
don't run md5 hash for files that have duplicate turned off
don't create empty byte allocation for completion of the hash (nil suffices as termninator)
set file.content to nil instead of empty byte allocation to free memory in the end
=> small cpu/mem optimizations

processor/processor.go, processor/structs.go, processor/workers.go, processor/workers_test.go
Changes tries to include the token type (string, comment, etc) in the leaves. This allows all the tokens to be packed into a single trie for codeState/blankState.
before: Time (mean ± σ):      1.437 s ±  0.013 s    [User: 21.352 s, System: 0.767 s]
after:  Time (mean ± σ):     826.1 ms ±  17.7 ms    [User: 11.270 s, System: 0.748 s]
Time (mean ± σ):      1.299 s ±  0.016 s    [User: 19.019 s, System: 0.764 s]
Time (mean ± σ):     575.7 ms ±  17.5 ms    [User: 7.140 s, System: 0.736 s]
=> merged trie for codeState/blankState

main.go
If invoking rootCmd.Execute() fails, e.g. due to a flag parsing error. Then
exit with a non-zero exit code.
Fixes: #44
=> Exit with non-zero outcome on command error

processor/file.go
This started as me trying to figure out why `scc --exclude-dir .git,vendor ~/go/src` wasn't actually excluding vendored code. It turns out the directory exclusions are only applied at the top level and also have to include the root if `.` isn't used.
When looking at the code I noticed that the exclusion regexp matching is _not_ done against full paths but is only compared to the directory entry's name so I attempted to use `scc --not-match '^vendor|\.git$ ~/go/src` which still didn't quite work. Adding `--verbose` showed that it was _claiming_ to be skipping the `.git` and `vendor` directories, so the pattern was working, but the logs also showed notices about files _inside_ those directories (eg. `HEAD`, `pack-*`, various unknown file extensions inside vendored paths).
The first patch …
=> Improve exclusion matching

main.go, processor/file.go, processor/processor.go, processor/workers.go
Modify scc to only load language features as required rather then doing all 222 in a single pass. 
Since the loading of features is a fairly heavy task the savings for the majority of cases is worth it. 
This is especially noticeable when working on smaller repositories.
Version 2.1.0 (with the update) vs 2.0.0 with the full load.
```
$ hyperfine './scc redis-5.0.2' && hyperfine 'scc redis-5.0.2'
Benchmark #1: ./scc redis-5.0.2
Time (mean ± σ):      81.6 ms ±   5.0 ms    [User: 173.8 ms, System: 265.4 ms]
Range (min … max):    75.5 ms …  97.1 ms
Benchmark #1: scc redis-5.0.2
Time (mean ± σ):     124.4 ms ±   2.4 ms    [User: 168.6 ms, System: 289.1 ms]
Range (min … max):   120.0 ms … 128.4 ms
```
NB this should be backwards compatible with library users as it is only enabled via the …
=> Lazy loading

main.go, processor/file.go, processor/file_test.go, processor/processor.go, test-all.sh
This patch allow to run the scc CLI with a single file path as an argument
rather than a directory.
I explicitly license my contribution under a choice MIT or The Unlicense.
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>
=> Accept a single file as a command line argument #54

processor/file.go
The original method of splitting a string with a "." to get a file extension in `getExtension` is complicated and unintuitive, so I reimplemented this function with filepath.Ext.
=> Simplify getExtension with filepath.Ext

processor/file.go, processor/file_test.go
The current .gitignore logic was pretty crappy, to the point it was effectively useless. I noticed that `scc` was needlessly walking things that should have been ignored and then usually discarding the results due to the whitelist.
This PR makes it work at the root level with the idea of building on it so that we can implement recursive .gitignore checks throughout the tree, and perhaps include hg ignore files in the future too. In short it is not meant to be the be all end all solution but at least gets the basics right.
In some cases this will improve performance and in others it will be worse, but more importantly it will improve relevance.
```
$ hyperfine './scc' 'scc'
Benchmark #1: ./scc
Time (mean ± σ):      33.2 ms ±   2.2 ms    [User: 32.6 ms, System: 102.4 ms]
Range (min … max): …
```
=> .gitignore improvements

processor/file.go, processor/file_test.go, processor/processor.go, test-all.sh
Implements request https://github.com/boyter/scc/issues/61 where you can pass in multiple files or directories on the command line and scc will process them as instructed. Biggest change is that the file walker is no longer responsible for closing its stream. This makes the code that spawns them a little more ugly since it now needs to have a waitgroup to track this but I don't seen an obvious way to improve it.
Appears to work over everything I tried. There may be the old ulimit issue again if the directories passed in are large enough, but I was not able to trigger it on my machine.
=> Add support to run over multiple files or directories

main.go, processor/file.go, processor/file_test.go, processor/processor.go
This is to address #67. It changes the `--not-match` argument to a `StringArray` to allow multiple exclusions to be passed.
I used `StringArray` rather than `StringSlice` since the latter splits on commas, and while I disapprove of commas in file names I think it's better to be tolerant. Besides, comma separating regular expressions could get ugly.
=> Make --exclude a StringArray argument

processor/workers.go, processor/workers_test.go
A fix for https://github.com/boyter/scc/issues/73
If a " was used inside a character it would trigger the string state. Quick fix is to check for \ before it and stay in the code state. 
Long term fix is to have a state for dealing with quotes, perhaps inside strings as they have the same rules. However this requires updating the whole JSON document and checking that quotes work like strings in all languages (unlikely). This seems like a good reasonable short term fix for most C like languages.
=> Resolve issue73 where quotes in character would trigger string state

processor/workers.go, processor/workers_regression_test.go, processor/workers_test.go
Don't actually want to merge this yet, as I belive the solution should be more generic but this does work to fix the issue in https://github.com/boyter/scc/issues/72
I am thinking that perhaps the full table of BOM https://en.wikipedia.org/wiki/Byte_order_mark#Byte_order_marks_by_encoding should be included in this to ensure that it works for all encoding types. No idea what impact that would have though. Is it even worth doing it for all of them?
Looking for ideas on this before it gets merged in for good to ensure its a solution that does not need to be revisited if possible.
=> Add test case and temp fix for issue72

README.md, main.go, test-all.sh
The naming of this option is unintuitive - it disables cocomo, but is named as if it would enable cocomo. Renaming it to be in line with the similar `--no-complexity`, `--no-gitignore`, etc.
```
$ GOPATH=~/code ./test-all.sh 
Running go fmt...
Running unit tests...
?   	github.com/boyter/scc	[no test files]
?   	github.com/boyter/scc/examples/language	[no test files]
ok  	github.com/boyter/scc/processor	1.137s
?   	github.com/boyter/scc/scripts	[no test files]
Building application...
Running integration tests...
Error: unknown flag: --not-a-real-option
Usage:
scc [flags]
Flags:
--avg-wage int            average wage value used for basic COCOMO calculation (default 56286)
--binary                  disable binary file detection
--by-file                 display output for every file
--ci …
```
=> rename the option that disables cocomo from '--cocomo' to '--no-cocomo'

README.md, processor/formatters.go
This came out simpler than expected because:
1. "reordering" only meant swapping the Blanks and Code columns. 
2. Only the tabularShortFormatNoComplexity format strings needed to be updated; Blanks and Code shared the same formatting directives in tabularShortFormat/tabularWideFormat modes.
I made a gist with output from each of the three formats running on the old version of scc, then edited them with output of each of the three formats from the new scc - the revision view shows a nice diff between the outputs:
https://gist.github.com/elindsey/a55888e1908789410967b92dfc57ded9/revisions
https://gist.github.com/elindsey/bfaa08a2dc3f77d253cb831f4d1fe3bf/revisions
https://gist.github.com/elindsey/357c48c798214f6613e1da6d038aa855/revisions
Test output follows:
```
$ GOPATH=~/code …
```
=> reorder fields in tabular output to match cloc

README.md
I added homebrew to the install docs. They were starting to get long, so I rearranged it a bit - let me know if you don't like the restructuring and I'll just tack it on to the existing text instead.
Might be easier to read the formatted version here https://github.com/elindsey/scc/tree/bmaster
=> add homebrew to install docs; rearrange install instructions

Gopkg.lock, Gopkg.toml, processor/file.go, processor/file_test.go, processor/processor.go, vendor/github.com/dbaggerman/cuba/README.md, vendor/github.com/dbaggerman/cuba/pool.go
Relates to #134.
I found an issue in `cuba`, which allowed it to create more workers than it was supposed to. This meant that the `DirectoryWalker` could have more directory handles open than it was supposed to. Depending on the directory layout, it may have been significantly more.
This pulls in the a version (`v0.3.2`) with the fix.
While I was at it, I also refactored `DirectoryWalker` so that the handles get closed as soon as possible, rather than being kept open until after the entries have been processed.
=> Reduce dir handles

packages/aur/PKGBUILD
Adding the package to AUR allows for easy installation for Arch Linux!
This file just needs to be submitted to https://aur.archlinux.org/
=> Add a PKGBUILD to submit to AUR

main.go, processor/formatters.go, processor/formatters_test.go, processor/processor.go, test-all.sh
Adds HTML output as an output option. I don't see too many people wanting this but it has been requested https://github.com/boyter/scc/issues/139
Supports all of the options that the command line does, except for the case of omitting complexity, although if you add that it sets it to 0 for everything.
Two modes, `html` and `html-table` where the former includes html and body tags IE a single HTML file ready to view (see screenshot) and the other which is designed to be embedded into another page and the user brings their own CSS.
=> Html output 139

languages.json
cljc files allow you to write code that is [portable between clojure dialects](https://clojure.org/guides/reader_conditionals). Many clojure projects use these files and not having them makes scc greatly under count how many lines a project has.
I explicitly licence my contribution under MIT AND The Unlicense.
=> Add cljc file extension for Clojure

processor/bloom.go, processor/processor.go, processor/structs.go, processor/workers.go
Looking at #241 made me wonder about how the extra tokens would effect our crude bloom filtering technique.
Turns out it only takes a handful of ASCII characters before the old bloom filter became 01111111 and matched everything. This implements a better bloom filter which drastically reduces collisions and makes the filter far more effective.
Since the new hashing takes a little more computation, using a lookup table is another modest improvement over recalculating every character processed.
Calculating hash values isn't an area of mathematics that I'm terribly familiar with, so there may be a better formula. But this seems to be a big improvement over the current implementation at least.
```
% hyperfine -r 50 './scc-master ../../torvalds/linux' './scc-new-bloom ../../torvalds/linux' …
```
=> New bloom filter

processor/bloom.go, processor/processor.go
Cleaned up to use `math/rand` to distribute the numbers rather than handrolled maths.
It seems like the better number distribution leads to a slightly more efficient bloom filter (as I suspected). It's not a huge improvement, but 2-3% faster is still a win.
```
Benchmark #1: ./scc-master ../../torvalds/linux
Time (mean ± σ):     699.7 ms ±   7.6 ms    [User: 9.277 s, System: 0.908 s]
Range (min … max):   683.8 ms … 716.0 ms    50 runs
Benchmark #2: ./scc-bloom2 ../../torvalds/linux
Time (mean ± σ):     678.1 ms ±   9.5 ms    [User: 8.846 s, System: 0.929 s]
Range (min … max):   653.0 ms … 698.4 ms    50 runs
Summary
'./scc-bloom2 ../../torvalds/linux' ran
1.03 ± 0.02 times faster than './scc-master ../../torvalds/linux'
```
=> Clean up new bloom filter implementation

examples/issue246.py, processor/file.go, processor/state_blank.go, processor/state_code.go, processor/state_comment_multi.go, processor/state_comment_single.go, processor/state_docstring.go, processor/state_string.go, processor/states.go, processor/structs.go, processor/workers.go
Since I've been back in the `scc` code, I got tempted to make an(other) attempt to break up the complexity in the `CountStats` state machine.
This changes from states being an enum, with all the state tracked in `CountStats` and passed in/out of the different methods to introduce a `State` interface with different states having their `stateXYZ` function moved to being attached to the relevant struct. This means we can drop the `switch` statement in the core loop and instead let the go runtime do the dispatch. It also lets relevant state be tracked in the `State` struct instead of being passed in and out of `CountStats`.
As a bonus, the different 'flavours' of `slComment` vs `slCommentCode`, etc are no longer required.
It seems to produce the same result in the examples I've thrown at it, …
=> Refactor CountStats state machine

README.md, go.mod, main.go, processor/file.go
Fixes https://github.com/boyter/scc/issues/237.
```
go get -u github.com/boyter/scc@v3.0.0
go get: github.com/boyter/scc@v3.0.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v3
```
This PR upgrades imports to include [SIV](https://github.com/golang/go/wiki/Modules#semantic-import-versioning) so that latest version can be imported as a module.
After merging, new minor or patch version (e.g. `v3.0.1`) can be tagged to solve the original issue.
=> Upgrade imports to match module version

main.go, processor/cocomo.go, processor/cocomo_test.go, processor/formatters.go, processor/processor.go
This commit makes the hard-coded overhead factor of 2.4 configurable by command line argument. Issue #281 is maybe related.
=> Add a overhead commandline flag to set the multiplier for corporate overhead. #281

main.go, processor/cocomo.go, processor/cocomo_test.go, processor/formatters.go, processor/processor.go
Here is another one for the effort adjustment factor (EAF). The EAF can be used to set deviating cost drivers with the predefined project type.
For example, if your project is rated (according to [dwheeler cost driver table](https://dwheeler.com/sloccount/sloccount.html#cocomo)) Very High for Complexity (effort multiplier of 1.30), and Low for Language & Tools Experience (effort multiplier of 1.07), and all of the other cost drivers are rated to be Nominal (effort multiplier of 1.00), the EAF is the product of 1.30 and 1.07.
Effort Adjustment Factor = EAF = 1.30 * 1.07 = 1.391
`scc --cocomo-project-type "organic" --eaf 1.391`
The eaf was hard-coded to a factor of 1 beforehand.
=> Add a command line argument for the effort adjustment factor.

processor/formatters.go
Basically this fixes a inconsistency in fileSummarizeShort() and fileSummarizeLong() and adds i18n support for number formats i.e. decimal and thousands separators.
```
$>./scc
...
Estimated Cost to Develop (organic) $667,319
Estimated Schedule Effort (organic) 11.79 months
Estimated People Required (organic) 5.03
$>LANG=de ./scc
...
Estimated Cost to Develop (organic) $667.319
Estimated Schedule Effort (organic) 11,79 months
Estimated People Required (organic) 5,03
```
At the moment I'm thinking about refactoring the COCOMO output to SLOCCount's output format, i.e. writing out the formula for calculating the values for better understanding of the printed values. But I'm unsure if this is something for a PR or a private branch...
=> Unify output of fileSummarizeShort() and fileSummarizeLong() and simple language support for number formats

main.go, processor/formatters.go, processor/processor.go
As mentioned in the previous PR, I've added a flag to output a more SLOCCount like COCOMO calculation. I prefer this one because you can see the formula and values used.
=> Add --sloccount-format flag to print a more SLOCCount like COCOMO calculation

processor/formatters.go
fixes issue introduced in #307
`aggregateLanguageSummary` returned `nil` instead of an empty slice in case of an empty input.
Fixes #308
=> fixed issues introduced in 4ef15e22

README.md
Updating the Github action tag, because there is an issue in `1.0.0` exporting the `scc` output into the Gtihub action steps.
=> Update documentation about Github action

main.go, test-all.sh
=> Add @file flag parsing syntax

languages.json
Fixes #359 and simplifies the MSBuild complexity check.
=> Improve msbuild

languages.json
The Julia complexity checks included a `switch` statement (which [does not currently exist](https://github.com/JuliaLang/julia/issues/18285) in Julia) but omitted `elseif` and `try/catch/finally` (unlike Python). 
Also, the Julia checks oddly included two comparison operators `==` and `!=`, which are not control flow (unlike the short-circuiting `&&` and `||`), are only two of the *many* comparison operators in Julia, and don't seem to be used as complexity measures by scc for Python.  So I deleted these two from the list.   Is there a good argument for why these should be included?   (I see that a number of languages, like Ruby and C++, do include them for some reason.) 
I also considered adding Julia's `->` and `do` operators which create [anonymous …
=> update Julia complexity checks

languages.json
Fixes Issue #362 
Source for 99% of the complexity stuff [is here in the Raku docs](https://docs.raku.org/language/control)
The all-caps ones are [Phasers](https://docs.raku.org/language/phasers) and I _think_ they should be included but I'm not 100% sure.
All the various quote marks come from [here in the grammar](https://github.com/rakudo/rakudo/blob/b5df6e28c4b1ebd2980174342c616e543c49a233/src/Perl6/Grammar.nqp#L3481)
except for `«` and `»` which are actually defined a few times in a few ways in the grammar (context alters meaning) Sometimes they function as quote marks. Sometimes they're...more. 
[edit]: added `react` and `whenever` from [the concurrency docs](https://docs.raku.org/language/concurrency#react).
Also of note is "emit" which is in the flow control docs but wasn't clear …
=> added Raku info to languages.json

README.md, processor/formatters.go, processor/formatters_test.go
The current output is valid for Prometheus, but not the derived OpenMetrics format:
- Spaces between comma-separated labels are not permitted
- The exposition must end with a `# EOF` line
- UNIT must be a suffix of the metric name, i.e. `scc_code` cannot have the unit `lines`
Additionally:
- Complexity is not measured in 'lines'
For reference, see:
https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md
I chose to remove the invalid `UNIT`s instead of renaming them to 1) not break people's monitoring and dashboards and 2) keep things consistent with the internal names, and names used in other output formats.
Ref #307, cc @jan-guenter
=> Make OpenMetrics output spec compliant

processor/formatters.go
Updated the csv-stream format to escape double quotes in the location and filename fields, then surround each field with double quotes.
This patches https://github.com/boyter/scc/issues/371
This submitted code is licensed under MIT AND The Unlicense.
=> Patch csv-stream format

README.md
=> README: remove duplicated noun in "it `scc`"

examples/issue345/filename.cc, processor/workers.go, test-all.sh
Previously, only one char got checked for escapes when parsing strings. This meant that strings such as "\\" never got terminated, leading to incorrect parsing.
This commit adds a check which calculates the number of escapes pre-string ending to determine wherever the last escape is itself escaped or not.
This was prompted by issue #345, I also added a test case for it.
One important note is that I am unsure how much that impacts performance.  The for loop is only accessed if the string has an escape before it, so it should be a fairly rare path.
=> Fix incorrect string escaping

.github/workflows/codeql-analysis.yml, .github/workflows/go.yml, README.md
- <https://github.com/rivo/uniseg> requires Go 1.18 for generics; use Go version found in `go.mod` for CI instead of Go 1.17.
- `actions/checkout@v2` uses Node 12 which is deprecated by GitHub; upgrade to `actions/checkout@v3`
---
This patch is licensed under MIT License and The Unlicense.
=> Fix CI: go.yml

processor/formatters.go, processor/formatters_test.go
This fixes an off-by-one when the filename length exactly matches our size limit. As an example, today if the filename size limit is one character and the filename is named "a", it will be incorrectly formatted as "~a" despite no truncation occuring.
=> do not add a '~' when filename is not truncated

processor/file.go
We should use `(*regexp.Regexp).MatchString` instead of `(*regexp.Regexp).Match([]byte(...))` when matching string to avoid unnecessary `[]byte` conversions and reduce allocations. A one-line change for free performance improvement.
Example benchmark:
```go
var excludeRegex = regexp.MustCompile("vendor")
func BenchmarkMatch(b *testing.B) {
for i := 0; i < b.N; i++ {
if match := excludeRegex.Match([]byte("vendor/pkg/main.go")); !match {
b.Fail()
}
}
}
func BenchmarkMatchString(b *testing.B) {
for i := 0; i < b.N; i++ {
if match := excludeRegex.MatchString("vendor/pkg/main.go"); !match {
b.Fail()
}
}
}
```
Result:
```
goos: linux
goarch: amd64
pkg: github.com/boyter/scc/v3/processor
cpu: AMD Ryzen 7 PRO 4750U with Radeon Graphics
BenchmarkMatch-16          	 4123592	       274.9 ns/op …
```
=> Avoid allocations with `(*regexp.Regexp).MatchString`

.github/workflows/docker-publish.yml, Dockerfile
This should solve the issue https://github.com/boyter/scc/issues/143 and help developpers who cannot install binaries to pull directly from github a docker image of scc.
I tested the workflow here https://github.com/lhoupert/scc-in-docker/pkgs/container/scc-in-docker and it seems to be working well.
A docker image will be created each time a new push is made on main or a tag is created.
=> Create Github action to automatically build a docker image and publish it in github package registry

.github/workflows/docker-publish.yml, Dockerfile, README.md
Hi,
Sorry I realised my previous pull request was wrong as the dockerfile was not relevant for a fork. 
I did some changes and tested, it seems to be working fine on my fork: https://github.com/lhoupert/scc/pkgs/container/scc 
You can test running the v0.0.2 of docker image generated on my fork with the command below :
```
docker run --rm -it -v "$PWD:/pwd"  ghcr.io/lhoupert/scc:v0.0.2 scc /pwd
```
This should fix the github action. Each new release of scc should also create a tagged docker image
=> Fix docker image build

languages.json
Many ILPROJ (Intermediate Language Project) files occur, for example, in https://github.com/dotnet/runtime. These are rather like CSPROJ files, and it seems they should be included in the MSBuild category. For some further discussion of ILPROJ, see https://github.com/dotnet/sdk/issues/16690.
=> Add lesser-known ILPROJ extension to MSBUILD

Dockerfile
Update Dockerfile to use alpine:3.20 both for builder and resulting image, caused by aquasec/trivy vuln. scanner issues with git, see #469
=> Update Dockerfile to use alpine:3.20

README.md, main.go
`pnpm-lock.yaml` is the file just like `package-lock.json` or `yarn.lock`
=> Add `pnpm-lock.yaml` to default exclude file list

main.go, processor/formatters.go, processor/formatters_test.go, processor/processor.go
This removes the horizontal border lines, making for more compact output.
For example:
% scc --min-gen --no-complexity --no-cocomo --no-size
───────────────────────────────────────────────────────────────────────────────
Language                     Files       Lines     Blanks    Comments      Code
───────────────────────────────────────────────────────────────────────────────
Go                              10        1374        114         199      1061
License                          1          20          4           0        16
Markdown                         1          94         23           0        71
YAML                             1           1          0           0         1
───────────────────────────────────────────────────────────────────────────────
Total …
=> Add --no-hborder

processor/formatters.go, processor/processor.go
`strings.EqualFold` is simpler and much faster than `strings.ToLower`.
=> Use strings.EqualFold in case-insensitive comparisons

main.go, processor/detector.go, processor/formatters.go, processor/processor_test.go, processor/workers.go, scripts/include.go
- **chore: remove unused parameters**
- **chore: fix Go comments**
- **chore: use simpler syntax**
- **chore: remove useless method**
- **chore: avoid type juggling**
- **chore: reduce complexity**
I used golangci with a lot of settings to detect many of the issues I report here
=> code review

processor/formatters.go, processor/processor.go
- replace `fmt.Println(fmt.Sprintf(...))` with `fmt.Printf`, this is simpler.
- replace `sb.WriteString(fmt.Sprintf(...))` with `fmt.Fprintf`, this is simpler and much faster:
```text
$ benchstat old.bench new.bench
goos: windows
goarch: amd64
pkg: testbuilder
cpu: Intel(R) Core(TM) i5-10200H CPU @ 2.40GHz
│  old.bench  │              new.bench              │
│   sec/op    │   sec/op     vs base                │
Builder-8   1.808µ ± 2%   1.533µ ± 1%  -15.19% (p=0.000 n=10)
│  old.bench   │              new.bench               │
│     B/op     │     B/op      vs base                │
Builder-8   1.281Ki ± 0%   1.000Ki ± 0%  -21.95% (p=0.000 n=10)
│  old.bench  │             new.bench              │
│  allocs/op  │ allocs/op   vs base                │
Builder-8   15.000 ± 0%   6.000 ± 0% …
```
=> improve: remove redundant calls of sprintf

processor/formatters.go
`count` was not a valid metric type and `gauge` is the better type since counters are expected to strictly increase.
An up to date Prometheus will complain about unknown metric types. 
See https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#type for valid types.
The doc says:
> Gauges are current measurements, such as bytes of memory currently used or the number of items in a queue. For gauges the absolute value is what is of interest to a user.
=> openmetrics formatter: emit gauge metrics

processor/formatters_test.go
#504 changed the OpenMetrics outputs but forgot changing the tests. Fit these tests into the correct output formats.
=> fix: fix OpenMetrics tests

SCC-OUTPUT-REPORT.html, cmd/badges/main.go, processor/detector.go, processor/formatters.go, scripts/include.go
Write tmp data to a buffer rather than a temp file. This is faster and robuster.
Fix some golangci-lint warnings.
Fix a miss use of break, a break in a switch only stop the switch statment, to stop the outer for-loop we need a label.
=> Enhance scripts/include.go and fix warnings

.gitattributes
This is a super-nitpicky PR, because I like to see syntax highlighting when I look at a file :sweat_smile: I think you're already familiar with linguist, but just to describe what this PR does:
- Applies Ignore List syntax highlighting to `.sccignore`
- If for whatever reason you decided to include Ignore List stats in the GitHub language bar, `.sccignore` would be counted to that.
=> Tell GitHub that `.sccignore` is an ignore list

README.md
I'm basically just copying good instructions that I've seen in other projects. What this does is add:
- `--id` option that ensures that `benboyter.scc` is the ID. Without this `benboyter.scc` is getting passed as a query instead of as a unique ID. This could potentially cause a similarly named package to get installed.
- `--source` option to specify that the `winget` repository should be used.
Personally, I *always* use the `--id` option with `winget`.
=> Make winget install more specific

processor/processor.go
tl;dr I discovered some weird Windows behavior where an invalid path causes `scc.exe` to panic. Surprisingly, the error is *not* a "does not exist" error. After some thought it seemed better to exit on *any* non-nil error.
In PowerShell, I tried to run `scc.exe *.go`, and to my surprise I got a panic. PowerShell did not expand the glob -- that's not scc's fault, although potentially [glob expansion can be added as a feature](https://pkg.go.dev/path/filepath#Glob) if that's reasonable. But the issue is that, on Windows, apparently this does *not* raise a "does not exist" error. So `os.Stat()` returns `nil, err` where `err` is *not* `nil`. So the call to `s.IsDir()` raises a nil pointer dereference error.
I did some playing around using the code below:
```go
package main
import "os"
import …
```
=> Catch any `os.Stat` error

SCC-OUTPUT-REPORT.html, cmd/badges/example.py, cmd/badges/main.go
Using standard libraries to get temp path and to do file operations.
This makes the program more simple and safer because standard libraries clean the path and no need to use outside commands.
It also makes the code more portable since not all systems use '/tmp' as its tempfile path (other places for example, '/data/local/tmp'). Many mordern Linux distros also support setting the env varibale '$TMPDIR' to change a program's tempfile path. So using the standard library's getTempDir function is a better idea, it's done all the works for us.
=> refactor: using standard libraries to do file operations

languages.json
It's a pretty common filename: https://github.com/search?q=path%3A%2F%28%5E%7C%5C%2F%29LICEN%28S%7CC%29E-APACHE%24%2F&type=code
You'll often see it in Rust projects, which are often MIT/Apache-2.0 dual-licensed.
=> Support `licen(c|s)e-apache`

cmd/badges/main.go, cmd/badges/main_test.go
Per issue #402 , it seemed like a quick win to add some url params for different badge settings
=> Added badge SVG customization URL query params and associated tests

README.md, main.go
Per issue #546 , corrected the parameter(--no-ignore) interpretation
=> corrected the parameter(--no-ignore) interpretation

SCC-OUTPUT-REPORT.html, cmd/badges/example.py, cmd/badges/main.go, processor/formatters.go
- simplify the usage of switch statements
- use "lang" and "langs" as aliases for "language" (these aliases are already used in existing code)
- reuse sortLanguageSummary
- use gettempdir to fix a warning about directly using the '/tmp' path
=> Simplify and clean up the code

cmd/badges/simplecache_test.go
The problem is triggered randomly, so I wrote a script to run this test 10,000 times in a row, and eventually found that it failed 6 times. And I also found out why it failed.
The script is:
```bash
for i in `seq 1 10000`
do
go test -run TestSimpleCache_Multiple | grep -A5 -B5 FAIL
done
```
Think about a cache after adding elements, it could has these keys: `["10", "499", "100", ... , "467"]` (This is possible because we randomly delete elements). Then we `simpleCache.Add("10", []byte{})`, `Add` will call `evictItems` because the cache already has 10 items, so one of them will be evicted. Because we randomly delete elements, the key "499" was evicted, then the cache only has 9 items left. Finally, `Add` uses `items["10"] = value` to add items, this does not change the number of elements …
=> Fix TestSimpleCache_Multiple

SCC-OUTPUT-REPORT.html, cmd/badges/main.go, processor/formatters.go, scripts/include.go
Currently, we have two JSON libraries in the code base: "encoding/json" and "github.com/json-iterator/go". Use one of them is completely enough.
The "json-iterator/go" is faster than the stdlib and uses less memory. So we choose the fast one for all JSON operations.
It also reduces the binary file size. For an example on Linux AMD64 with Go1.22.7, the binary file change is `8988568 -> 8811060 bytes`, more than 150 kib was reduced.
=> Use json-iterator/go for all JSON operations

SCC-OUTPUT-REPORT.html, processor/formatters.go, processor/formatters_test.go
Linux asks all text files end with a newline. Git also need this:
Fix some indentations that mixed tabs and spaces.
=> Add a newline to output files

SCC-OUTPUT-REPORT.html, cmd/badges/simplecache_test.go, processor/formatters.go
"strconv.FormatInt" is faster and does less allocations than "fmt.Sprint". Let's do the right thing with the right tools.
benchmark:
go version 1.23.4
```golang
func BenchmarkFmtSprint(b *testing.B) {
for i := range b.N {
_ = fmt.Sprint(i)
}
}
func BenchmarkStrconv(b *testing.B) {
for i := range b.N {
strconv.FormatInt(int64(i), 10)
}
}
```
=> Use a faster method to convert ints to strings

README.md
Fixing link to GitLab docs actually not existing
=> (docs) fix GitLab CI link to metrics reports

README.md
Fix #589
Not sure where to put Fedora, so I'm just sticking it in the middle. 
It might be nicer to have the README organized with `<details>` and `<summary>` tags so that sections become collapsible and the page won't be too long to be navigable. Users would be able to quickly find information relevant to their own OS. For example:
<details>
<summary>
</summary>
You can install `scc` by using the standard go toolchain.
To install the latest stable version of scc:
`go install github.com/boyter/scc/v3@latest`
To install a development version:
`go install github.com/boyter/scc/v3@master`
Note that `scc` needs go version >= 1.22.
</details>
<details>
<summary>
</summary>
Lorem ipsum
Lorem ipsum
Lorem ipsum
</details>
<details>
<summary>
</summary>
Lorem ipsum
</details>
<details>
<summary> …
=> Add fedora install instructions in README

.devcontainer/devcontainer.json
"mcr.microsoft.com/devcontainers/go" finally released their go1.24 support.
=> Update devcontainer to support go1.24

languages.json, processor/constants.go
Fixes the issue of line comments not being counted by using \# as the line comment symbol instead of //.
https://github.com/boyter/scc/issues/611
This contribution is licensed under the present MIT License.
=> Fix line comment count for nix (#611)

SCC-OUTPUT-REPORT.html, languages.json, processor/constants.go
.Net 10 allows running a single C# file without project config. Here is the example: <https://devblogs.microsoft.com/dotnet/announcing-dotnet-run-app/#using-shebang-lines-for-shell-scripts>
=> feat: Support .Net 10 CSharp shebang

README.md, processor/formatters.go
Makes it more readable for short summary, just like for the "Estimated Cost to Develop" like:
10,000,000 instead of 10000000
fixes #335
+ Markdown fixes
=> feat: format numbers using current locale

README.md
Update the readme with the new result of `scc -a -i c redis`.
I forgot to do that in PR #662
=> doc: missing new formatting delivered in #335

SCC-OUTPUT-REPORT.html, test-all.sh
Run `./scc "examples/language/" --no-scc-ignore` once then reuse its result on the specific languages test. Otherwise we would need to run SCC hundreds of times over and over in an increasingly complex directory, and even though SCC is very fast it would significantly increase the time spent on testing.
The time taken to run `test-all.sh` on my laptop went down from 11.5s to 9.7s.
=> feat: speed up specific languages test

SCC-OUTPUT-REPORT.html, processor/workers.go
The compiler is still not smart, branch-less code in `CountStats` casused a performance regression. I'll revert this part.
Other parts won't impact the speed.
Before:
Fixes:
After the revert the performance issue is fixed and we even become a little bit faster.
The compiler reports that these functions are inlined (I also detected the binary file, printXXX functions actually inlined and they were not in the symbol table), and theoretically there should be no performance difference. This is so wierd, so I left some comments on it.
=> fix: fix CountStats performance

README.md
This PR fixes a minor spelling error ('busin esses' to 'businesses') in the README file. According to the contribution guidelines, I licence my contribution under MIT licence.
=> Docs: Fix typo in 'scc for Teams & Enterprise' section of README.md

SCC-OUTPUT-REPORT.html, processor/filereader.go, processor/formatters.go, processor/workers.go, scripts/include.go
Fix some warnings:
I did not remove the unused code because it was added recently and maybe useful in future.
=> refactor: fix some golangci-lint warnings

SCC-OUTPUT-REPORT.html, processor/formatters.go
Fixes #635 
The display misalignment is caused by the missing changes of some output templates in #632. The issue can be resolved by aligning these templates according to the new width.
After fixing:
Additionally, I noticed that ULOC-related numbers aren't outputting in the local format. I'll address this issue in another pull request; this one focuses solely on fixing output alignment.
=> fix: correct spacing padding

SCC-OUTPUT-REPORT.html, processor/structs.go, processor/structs_test.go
Fixes #645
Reduce `Language` size from 208 to 200 bytes by reordering fields. This can save some memory since we already have 350+ languages.
=> fix: Remove ComplexityLine from JSON output
